version: '3.3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper-tmc
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka-tmc
    ports: 
      - "9092:9092"
    environment: 
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181